package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"

	"github.com/manasa086/supportpilot-ai-inbox/api/graph/model"
	"github.com/manasa086/supportpilot-ai-inbox/api/internal/store"
	"github.com/manasa086/supportpilot-ai-inbox/api/internal/triage"
)

// Tickets is the resolver for the tickets field.
func (r *accountResolver) Tickets(ctx context.Context, obj *model.Account) ([]*model.Ticket, error) {
	tickets, err := r.Store.ListTicketsByAccount(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("listing tickets for account %q: %w", obj.ID, err)
	}
	return toTicketModels(tickets), nil
}

// Summary is the resolver for the summary field.
func (r *accountResolver) Summary(ctx context.Context, obj *model.Account) (*string, error) {
	// MVP: return whatever's cached on the account record. The stretch
	// goal is computing this lazily via a second Bedrock call over the
	// account's ticket history and caching it with Store.SetAccountSummary
	// — not wired up yet.
	return obj.Summary, nil
}

// CreateTicket is the resolver for the createTicket field.
func (r *mutationResolver) CreateTicket(ctx context.Context, input model.CreateTicketInput) (*model.Ticket, error) {
	t, err := r.Store.CreateTicket(ctx, store.NewTicketInput{
		AccountID:      input.AccountID,
		Subject:        input.Subject,
		Body:           input.Body,
		RequesterEmail: input.RequesterEmail,
	})
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("account %q not found", input.AccountID)
		}
		return nil, fmt.Errorf("creating ticket: %w", err)
	}
	return toTicketModel(t), nil
}

// TriageTicket is the resolver for the triageTicket field.
func (r *mutationResolver) TriageTicket(ctx context.Context, id string) (*model.Ticket, error) {
	t, err := r.Store.GetTicket(ctx, id)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("ticket %q not found", id)
		}
		return nil, fmt.Errorf("loading ticket %q: %w", id, err)
	}

	account, err := r.Store.GetAccount(ctx, t.AccountID)
	if err != nil {
		return nil, fmt.Errorf("loading account %q for ticket %q: %w", t.AccountID, id, err)
	}

	result, err := r.Classifier.Triage(ctx, triage.Input{
		Subject:     t.Subject,
		Body:        t.Body,
		AccountName: account.Name,
		AccountPlan: account.Plan,
	})
	if err != nil {
		return nil, fmt.Errorf("triaging ticket %q: %w", id, err)
	}

	t.Category = &result.Category
	t.Priority = &result.Priority
	t.Status = "TRIAGED"
	t.Suggestion = &store.Suggestion{
		Category:   result.Category,
		Priority:   result.Priority,
		Reply:      result.Reply,
		Confidence: result.Confidence,
	}

	if err := r.Store.UpdateTicket(ctx, t); err != nil {
		return nil, fmt.Errorf("saving triage result for ticket %q: %w", id, err)
	}
	return toTicketModel(t), nil
}

// ResolveTicket is the resolver for the resolveTicket field.
func (r *mutationResolver) ResolveTicket(ctx context.Context, id string) (*model.Ticket, error) {
	t, err := r.Store.GetTicket(ctx, id)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("ticket %q not found", id)
		}
		return nil, fmt.Errorf("loading ticket %q: %w", id, err)
	}
	t.Status = "RESOLVED"
	if err := r.Store.UpdateTicket(ctx, t); err != nil {
		return nil, fmt.Errorf("resolving ticket %q: %w", id, err)
	}
	return toTicketModel(t), nil
}

// Tickets is the resolver for the tickets field.
func (r *queryResolver) Tickets(ctx context.Context, status *model.TicketStatus, priority *model.TicketPriority) ([]*model.Ticket, error) {
	filter := store.TicketFilter{}
	if status != nil {
		s := string(*status)
		filter.Status = &s
	}
	if priority != nil {
		p := string(*priority)
		filter.Priority = &p
	}
	tickets, err := r.Store.ListTickets(ctx, filter)
	if err != nil {
		return nil, fmt.Errorf("listing tickets: %w", err)
	}
	return toTicketModels(tickets), nil
}

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, id string) (*model.Ticket, error) {
	t, err := r.Store.GetTicket(ctx, id)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("loading ticket %q: %w", id, err)
	}
	return toTicketModel(t), nil
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context) ([]*model.Account, error) {
	accounts, err := r.Store.ListAccounts(ctx)
	if err != nil {
		return nil, fmt.Errorf("listing accounts: %w", err)
	}
	return toAccountModels(accounts), nil
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, id string) (*model.Account, error) {
	a, err := r.Store.GetAccount(ctx, id)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("loading account %q: %w", id, err)
	}
	return toAccountModel(a), nil
}

// Account is the resolver for the account field.
func (r *ticketResolver) Account(ctx context.Context, obj *model.Ticket) (*model.Account, error) {
	accountID, ok := ticketAccountID(obj.ID)
	if !ok {
		return nil, fmt.Errorf("ticket %q has a malformed id", obj.ID)
	}
	a, err := r.Store.GetAccount(ctx, accountID)
	if err != nil {
		return nil, fmt.Errorf("loading account %q for ticket %q: %w", accountID, obj.ID, err)
	}
	return toAccountModel(a), nil
}

// Account returns AccountResolver implementation.
func (r *Resolver) Account() AccountResolver { return &accountResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Ticket returns TicketResolver implementation.
func (r *Resolver) Ticket() TicketResolver { return &ticketResolver{r} }

type (
	accountResolver  struct{ *Resolver }
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	ticketResolver   struct{ *Resolver }
)
