// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// A customer account. In DynamoDB this is the PK=ACCOUNT#id item.
type Account struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Plan      string    `json:"plan"`
	Seats     int32     `json:"seats"`
	CreatedAt time.Time `json:"createdAt"`
	Tickets   []*Ticket `json:"tickets"`
	// Lazily-resolved LLM summary of this account's ticket history (stretch goal).
	Summary *string `json:"summary,omitempty"`
}

type CreateTicketInput struct {
	AccountID      string `json:"accountId"`
	Subject        string `json:"subject"`
	Body           string `json:"body"`
	RequesterEmail string `json:"requesterEmail"`
}

type Mutation struct {
}

type Query struct {
}

// The AI-generated triage result for a ticket.
type Suggestion struct {
	Category   string         `json:"category"`
	Priority   TicketPriority `json:"priority"`
	Reply      string         `json:"reply"`
	Confidence float64        `json:"confidence"`
}

// A support ticket. In DynamoDB this is the PK=ACCOUNT#id, SK=TICKET#id item.
type Ticket struct {
	ID             string          `json:"id"`
	Account        *Account        `json:"account"`
	Subject        string          `json:"subject"`
	Body           string          `json:"body"`
	Status         TicketStatus    `json:"status"`
	Priority       *TicketPriority `json:"priority,omitempty"`
	Category       *string         `json:"category,omitempty"`
	RequesterEmail string          `json:"requesterEmail"`
	CreatedAt      time.Time       `json:"createdAt"`
	UpdatedAt      time.Time       `json:"updatedAt"`
	// Present once triageTicket has been run.
	Suggestion *Suggestion `json:"suggestion,omitempty"`
}

type TicketPriority string

const (
	TicketPriorityLow    TicketPriority = "LOW"
	TicketPriorityMedium TicketPriority = "MEDIUM"
	TicketPriorityHigh   TicketPriority = "HIGH"
	TicketPriorityUrgent TicketPriority = "URGENT"
)

var AllTicketPriority = []TicketPriority{
	TicketPriorityLow,
	TicketPriorityMedium,
	TicketPriorityHigh,
	TicketPriorityUrgent,
}

func (e TicketPriority) IsValid() bool {
	switch e {
	case TicketPriorityLow, TicketPriorityMedium, TicketPriorityHigh, TicketPriorityUrgent:
		return true
	}
	return false
}

func (e TicketPriority) String() string {
	return string(e)
}

func (e *TicketPriority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TicketPriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TicketPriority", str)
	}
	return nil
}

func (e TicketPriority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TicketPriority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TicketPriority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TicketStatus string

const (
	TicketStatusNew        TicketStatus = "NEW"
	TicketStatusTriaged    TicketStatus = "TRIAGED"
	TicketStatusInProgress TicketStatus = "IN_PROGRESS"
	TicketStatusResolved   TicketStatus = "RESOLVED"
)

var AllTicketStatus = []TicketStatus{
	TicketStatusNew,
	TicketStatusTriaged,
	TicketStatusInProgress,
	TicketStatusResolved,
}

func (e TicketStatus) IsValid() bool {
	switch e {
	case TicketStatusNew, TicketStatusTriaged, TicketStatusInProgress, TicketStatusResolved:
		return true
	}
	return false
}

func (e TicketStatus) String() string {
	return string(e)
}

func (e *TicketStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TicketStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TicketStatus", str)
	}
	return nil
}

func (e TicketStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TicketStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TicketStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
